# Sync seanh's Pocket account to seanh's Pinboard account.
name: "Sync seanh"
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
concurrency:
  group: seanh
jobs:
  Sync:
    uses: ./.github/workflows/sync.yml
    secrets:
      POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
      POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
      PINBOARD_AUTH_TOKEN: ${{ secrets.PINBOARD_AUTH_TOKEN }}
  Keepalive:
    needs: sync
    runs-on: ubuntu-latest
    steps:
    - run: gh workflow enable --repo '${{ github.repository }}' '.github/workflows/sync.yml'
      env:
        GH_TOKEN: ${{ secrets.github_token }}
