on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
concurrency:
  group: sync
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python3 -m venv .venv
      - run: .venv/bin/pip install -r requirements.txt
      - run: .venv/bin/python pocket_to_pinboard.py
        env:
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
          PINBOARD_AUTH_TOKEN: ${{ secrets.PINBOARD_AUTH_TOKEN }}
      - run: gh workflow enable --repo '${{ github.repository }}' '.github/workflows/sync.yml'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
